/* COCHES */
export const CARS = [
  {
    id: "clio",
    title: "Renault Clio RT 1.4 80 cv",
    brand: "Renault",
    year: 1994,
    km: 86000,
    price: 2500,
    fuel: "Gasolina",
    transmission: "Automático",
    location: "Mora (Toledo)",
    sold: false,
    description:
      "Vehículo en muy buen estado, con mantenimiento al día: cambio de bujías, aceite y filtro. Consumo bajo, ideal para ciudad y carretera.",
    photos: [
      "img/clio.jpeg",
      "img/clio2.jpeg",
      "img/clio3.jpeg",
      "img/clio4.jpeg",
      "img/clio5.jpeg",
      "img/clio6.jpeg",
    ],
  },
  {
    id: "Volkswagen",
    title: "Volkswagen Golf GTI DSG performance 2.0 230cv",
    brand: "Volkswagen",
    year: 2013,
    km: 163000,
    price: 18000,
    fuel: "Gasolina",
    transmission: "Manual",
    location: "Mora (Toledo)",
    sold: false,
    description:
      "Vehículo en muy buen estado, con mantenimiento al día: cambio de bujías, aceite y filtro. Consumo bajo, ideal para ciudad y carretera.",
    photos: [
      "img/her.jpeg",
      "img/her(1).jpeg",
      "img/her(3).jpeg",
      "img/her(4).jpeg",
      "img/her(7).jpeg",
      "img/her(9).jpeg",
      "img/herm8.jpeg",
    ],
  },
  {
    id: "peugeot208",
    title: "Peugeot 208 1.2 110 cv",
    brand: "Peugeot",
    year: 2016,
    km: 103000,
    price: 7500,
    fuel: "Gasolina",
    transmission: "Manual",
    location: "Mora (Toledo)",
    sold: true,
    description:
      "Coche perfecto para circular tanto en ciudad como en carretera. Vehículo muy económico y de bajo consumo, con distribución, aceite y filtros recién hechos. ITV en vigor hasta 2027.",
    photos: [
      "img/peugeot1.jpeg",
      "img/peu2.jpeg",
      "img/peu3.jpeg",
      "img/peu4.jpeg",
      "img/peu5.jpeg",
      "img/peu6.jpeg",
      "img/peu7.jpeg",
      "img/peu8.jpeg",
      "img/peu9.jpeg",
      "img/peu10.jpeg",
    ],
  },
  {
    id: "c4cactus",
    title: "Citroën C4 Cactus 1.6 92 cv",
    brand: "Citroën",
    year: 2014,
    km: 133000,
    price: 8000,
    fuel: "Diésel",
    transmission: "Automático",
    location: "Mora (Toledo)",
    sold: true,
    description:
      "Automático, cómodo y económico. Interior limpio, sin golpes, excelente conducción.",
    photos: [
      "img/c41.jpeg",
      "img/c42.jpeg",
      "img/c43.jpeg",
      "img/c44.jpeg",
      "img/c45.jpeg",
      "img/c46.jpeg",
      "img/c47.jpeg",
    ],
  },
  {
    id: "bmw1",
    title: "BMW Serie 1 2.0 143 cv",
    brand: "BMW",
    year: 2008,
    km: 364000,
    price: 2500,
    fuel: "Diésel",
    transmission: "Manual",
    location: "Mora (Toledo)",
    sold: true,
    description:
      "Vehículo utilitario ideal para el día a día, con motor en perfecto estado y revisiones al día. Vehículo nacional, de único propietario y con un consumo muy económico.",
    photos: ["img/bmw.jpeg"],
  },
];
